name: orientation_helper
description: A new Flutter package project.
version: 1.0.0
homepage: https://github.com/sergiyvergun/orientation_helper

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  # Linter
  pedantic: ^1.9.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:


